const ProductData = [
    {
        id:1,
        category:2,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    },
    {
        id:1,
        category:3,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    },
    {
        id:1,
        category:3,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    },
    {
        id:1,
        category:2,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    },
    {
        id:1,
        category:3,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    },
    {
        id:1,
        category:3,
        description:'Description',
        image:'',
        rating:'',
        reviewCount:'',
        price:''
    }
]

export default ProductData;